name: Deploy ADF

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev, Test, or prod)'
        required: true
        type: string
        options:
          - dev
          - Test
          - prod

jobs:
  deploy-dev:
    if: ${{ github.event.inputs.environment == 'dev' }}
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Run Dev Deployment
        run: echo "Running Dev Deployment"
      # Add actual dev deployment steps here

  deploy-test:
    if: ${{ github.event.inputs.environment == 'Test' || github.event.inputs.environment == 'prod' }}
    name: Deploy to Test
    runs-on: ubuntu-latest
    environment: Test

    steps:
      - name: Run Test Deployment
        run: echo "Running Test Deployment"
      # Add actual test deployment steps here

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: deploy-test
    environment: production

    steps:
      - name: Run Prod Deployment
        run: echo "Running Prod Deployment"
      # Add actual prod deployment steps here

      - name: Deploy ADF
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_APP_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az deployment group create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file adf-nip-dev-eus/ARMTemplateForFactory.json \
            --parameters adf-nip-dev-eus/ARMTemplateParametersForFactory.json \
            --name "ADF-Deployment-${{ github.run_number }}-prod"
