name: Deploy ADF

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev)'
        required: true
        type: string
        options:
          - dev

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Run Dev Deployment
        run: echo "Running Dev Deployment"
      # Add actual dev deployment steps here

  deploy-test:
    name: Deploy to Test (Approval Required)
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: test  # Must be configured with required reviewers in GitHub Environments

    steps:
      - name: Run Test Deployment
        run: echo "Running Test Deployment"
      # Add actual test deployment steps here

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: deploy-test
    environment: production

    steps:
      - name: Run Prod Deployment
        run: echo "Running Prod Deployment"
      # Add actual prod deployment steps here

      
